BBPATH .= ":${LAYERDIR}"
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "cosmopod"
BBFILE_PATTERN_cosmopod = "^${LAYERDIR}/"
BBFILE_PRIORITY_cosmopod = "20"

LAYERSERIES_COMPAT_cosmopod = "wrynose"
LAYERDEPENDS_cosmopod = "core raspberrypi mender openembedded-layer meta-python networking-layer filesystems-layer multimedia-layer"

WKS_FILE_PATH:append := ":${LAYERDIR}/wic"
