[Unit]
Requires=cosmopod-seatd.service
After=cosmopod-seatd.service

[Service]
Environment=LIBSEAT_BACKEND=seatd
ExecStart=
ExecStart=/usr/bin/weston --backend=drm --renderer=pixman --continue-without-input --modules=systemd-notify.so --log=/run/user/1000/weston.log
StandardOutput=journal+console
StandardError=journal+console
