PasswordAuthentication no
KbdInteractiveAuthentication no
PermitEmptyPasswords no
PermitRootLogin no
PubkeyAuthentication yes
AuthenticationMethods publickey
AllowUsers cosmopod

HostKey /data/cosmopod/ssh/ssh_host_ed25519_key
HostKey /data/cosmopod/ssh/ssh_host_rsa_key
